### ISSUE TITLE
TypeError : an integer is required error

### ISSUE THREAD

**Issue by apiszcz** [honeyext/cdtw#1]
I get this error with the speedtest and here.

(Pdb) dtw([1,2,3],[2,3,4],Settings(dist='manhattan', step  = 'dp2', window = 'nowindow', compute_path = True))
**\* TypeError: an integer is required

**Comment by halachkin** [comment]
It is fixed, try it now. 
speedtest was something, that I have hot planned to provide, you can run test/test.py to verify that it's working. Thx for the report

**Comment by apiszcz** [comment]
it looks like the only change is the .pyx, do I need to recompile or just
use the .pyx? Thanks.​

**Comment by halachkin** [comment]
.pyx is [cython](http://cython.org/docs/0.22/#) code, you need to compile it
