### ISSUE TITLE
AttributeError: Step instance has no attribute 'set_type'

### ISSUE THREAD

**Issue by apiszcz** [honeyext/cdtw#2]
C:\p\SonicEvents>lib\python\python.exe speedtest.py
Traceback (most recent call last):
  File "speedtest.py", line 16, in <module>
    s.step.set_type('dp2')
AttributeError: Step instance has no attribute 'set_type'

**Comment by halachkin** [comment]
see https://github.com/honeyext/cdtw/issues/1#issuecomment-98174915
Thanks for the report
