### ISSUE TITLE
set_type in test.py, and integer error

### ISSUE THREAD

**Issue by apiszcz** [honeyext/cdtw#3]
C:\Users\p\Downloads>python test.py
Traceback (most recent call last):
  File "test.py", line 280, in <module>
    run(s,t)
  File "test.py", line 63, in run
    s.step.set_type('dp2')
AttributeError: Step instance has no attribute 'set_type'
# 

C:\Users\p\Downloads>python test.py
Traceback (most recent call last):
  File "test.py", line 280, in <module>
    run(s,t)
  File "test.py", line 67, in run
    d = dtw(ref,query,s)
  File "C:\Users\ap\Downloads\cdtw\src\pydtw.py", line 11, in **init**
    cydtw.**init**(self, ref, query, settings)
  File "cydtw.pyx", line 250, in cydtw.cydtw.**init** (cydtw.c:4337)
    self._dtw(ref, query, settings)
  File "cydtw.pyx", line 259, in cydtw.cydtw._dtw (cydtw.c:4588)
    c_dtw_settings.dist_type = <int > settings.dist.get_cur_type_code()
TypeError: an integer is required

This is resolved with:
python setup.py build_ext --inplace --compiler=msvc

TEST PASSED
C:\Users\p\Downloads>python test.py
Ran 20 tests. 0 failures.

**Comment by halachkin** [comment]
Hmm, it works nice for me. Could you please give me some more information?

**Comment by apiszcz** [comment]
I'm running test.py with python test.py.
The error states there is no set_type.
What other information can I supply?
Thanks.

On Sat, May 2, 2015 at 1:39 PM, Aliaksei Halachkin <notifications@github.com

**Comment by halachkin** [comment]
How do you compile it? Which python, cython and C compiler do you use?

**Comment by apiszcz** [comment]
Python 2.7.9 64 bit
C:\Users\p\Downloads>vcvarsall.bat
Setting environment for using Microsoft Visual Studio 2008 x86 tools.
C:\Users\p\Downloads>cython -V
Cython version 0.22

http://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by halachkin** [comment]
I really don't know where is a problem :) Try download it again, and recompile:
cmd>python setup.py build_ext --inplace --compiler=msvc
If you will fix it, say me how. In the first post, you provided two different errors, it seems, that I've fixed them both.
