### ISSUE TITLE
Different distances when compute_path=True/False?

### ISSUE THREAD

**Issue by johanneshk** [honeyext/cdtw#4]
Hi!

I don't understand the following behavior (code adapted from examples nb):

```
import numpy as np
import pydtw
t = np.arange(0,3*np.pi,0.2)
r = np.sin(t)
q = np.cos(1.2*t+1) + np.sin(t)
print(pydtw.dtw(r,q,pydtw.Settings(dist = 'manhattan', step  = 'dp2', window = 'nowindow', compute_path = True)).get_dist())
print(pydtw.dtw(r,q,pydtw.Settings(dist = 'manhattan', step  = 'dp2', window = 'nowindow', compute_path = False)).get_dist())
```

Output:

```
12.37014033416319
11.829838028295049
```

Why do I get different distance when setting compute_path to True or False? Shouldn't the distances be the same regardless (maybe I'm missing something...)?

Thanks!

**Comment by halachkin** [comment]
Hello, 

You are right, there was a great bug. Thank you for your attention. I have fixed it, try it now. 
The code is pretty dirty, I have in plans to redesign it :)

Best regards

**Comment by johanneshk** [comment]
Yes, at least now I get the same distances ;) . I really like this project as it seems to be the most complete and convenient pydtw library. So thank you for your work.
