### ISSUE TITLE
Create a pip package?

### ISSUE THREAD

**Issue by johanneshk** [honeyext/cdtw#5]
I wonder if you are interested in creating a package for pypi? That would be great, as it would greatly simplify installation (pip install cdtw) and usage.

**Comment by halachkin** [comment]
Hi, johanneshk!
Sorry for my late reply. Of course I had thought about it, but I had never create packages before, and I am not familiar with it. I have not so much time at the moment, but  I am planning to upgrade the library (probably move it to the C++, include some more complicated algorithms like dtw for sub sequences, multiscaling (a.k.a FastDTW) and make pypi package. I am not satisfied with my code and pypi package has lower priority for me now :D
But if you have some experience in package creating you are welcomed to make pull request)

**Comment by johanneshk** [comment]
Same here: No experience packaging stuff ;) . Although I want to do this in the near future so maybe I'll take a shot.

**Comment by maybelinot** [comment]
@honeyext 
Just follow the [instruction](http://peterdowns.com/posts/first-time-with-pypi.html)
It's pretty simple

**Comment by johanneshk** [comment]
@honeyext 
After a lot of try and error I think I now got a version that can be installed using pip:
https://github.com/johanneshk/cdtw

```
pip install git+https://github.com/johanneshk/cdtw.git
```

Let me know if this works! I don't know how 'good' my solution is, since this is my first time doing this. Also the cython part complicated things a bit.

**Comment by maybelinot** [comment]
It isn't the best solution, because you just using pip environment to install package from git repo, it's equivalent to: 
1. clone repository
2. install with setup.py file

For normal pip installation you should register package on PyPi, so you can install it simply by name of your package(pip install cdtw).. And I suggest to leave it for @honeyext so he will be maintainer of this package and will be able to update new versions on PyPi server..

**Comment by halachkin** [comment]
@johanneshk, your solution works for me too. I made some modifications, now it is possible to install without cython too. Thank you a lot. I have also registered package on the PyPi (pip install cdtw).
@maybelinot  thanks for the nice link.

**Comment by johanneshk** [comment]
Nice, works for me as well! Thanks!
